language: php

php:
  - 7.3
  - 7.4
  - 8.0

env:
  - SYMFONY_VERSION=3.4.*
  - SYMFONY_VERSION=4.4.*

sudo: false
dist: bionic

cache:
  directories:
    - $HOME/.composer/cache/files

matrix:
  exclude:
    - php: 8.0
      env: SYMFONY_VERSION=3.4.*

before_install:
  - composer self-update
  - composer require -n --prefer-dist "symfony/symfony:${SYMFONY_VERSION}"

script:
  - php -v
  - composer test

after_success:
  - bash <(curl -s https://codecov.io/bash)
